# Generated by Django 5.1 on 2024-11-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_avaliacao_comentario_fila_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='avaliacao',
        ),
        migrations.DeleteModel(
            name='Fila',
        ),
    ]
