# Generated by Django 5.1 on 2024-11-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_remove_comentario_avaliacao_delete_fila'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='data_comentario',
            new_name='data',
        ),
    ]
