# Generated by Django 5.1 on 2024-11-01 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_rename_data_comentario_comentario_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='dislikes',
            field=models.ManyToManyField(related_name='comentario_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='likes',
            field=models.ManyToManyField(related_name='comentario_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
