# Generated by Django 5.1 on 2024-11-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_comentario_dislikes_comentario_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='likes',
        ),
    ]
